### ISSUE TITLE
Non null-safety version?

### ISSUE THREAD

**Issue by xJon** [PegasisForever/keep_keyboard_popup_menu#1]
Hi, thank you for making this useful package.
I'm opening this issue to ask whether it was considered to publish a non null-safety version, for Flutter projects that are on the stable channels.
Thank you!

**Comment by PegasisForever** [comment]
I'll work on it later and publish it tomorrow.

**Comment by PegasisForever** [comment]
I published the non null-safety version as `1.0.1`, the original null-safety version is renamed to `2.0.0-nullsafety.0`.

**Comment by xJon** [comment]
> I published the non null-safety version as `1.0.1`, the original null-safety version is renamed to `2.0.0-nullsafety.0`.

Thank you so much for the speedy work!
I'm trying to build my app with the package but I'm getting this error:
> /C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/keep_keyboard_popup_menu-1.0.1/lib/src/keep_keyboard_popup_menu_button.dart:48:38: Error: Getter not found: 'adaptive'.
            icon: icon ?? Icon(Icons.adaptive.more),
                                     ^^^^^^^^
FAILURE: Build failed with an exception.

Any idea what causes this?

**Comment by PegasisForever** [comment]
Which version of flutter are you using?

**Comment by PegasisForever** [comment]
Provide it an icon explicitly should work fine.

**Comment by PegasisForever** [comment]
Hold on, seems like `Icons.adaptive` is not yet in stable flutter.

**Comment by xJon** [comment]
That would make sense, I am using Flutter `1.22.6`.

**Comment by PegasisForever** [comment]
Just released `1.0.2`, fixed this issue. Thanks for reporting!

**Comment by xJon** [comment]
Thanks again for the package!
