### ISSUE TITLE
Dismissing popupmenu before keyboard hiding

### ISSUE THREAD

**Issue by Bubu** [PegasisForever/keep_keyboard_popup_menu#4]
Hi, thank you so much for this package, it makes a very annoying thing about flutter tolerable! :)

I have one question though, when I have the keyboard visible and the popupmenu open, pressing the android back-button first hides the keyboard before navigating back. The usual Android behaviour would be first dimissing the popup before hiding the keyboard before navigating back.

Would such a behaviour be possible to add to the package or at the app side?

**Comment by PegasisForever** [comment]
I have no idea how to implement it in the package. Basically you need to intercept the back button event, cancel the flutter default behaviour (close keyboard) and close the popup instead.

Afaik there is no way in flutter to intercept the back button event when the keyboard is open, flutter will always close the keyboard first. (I've looked into [WillPopScope](https://api.flutter.dev/flutter/widgets/WillPopScope-class.html) and [back_button_interceptor](https://pub.dev/packages/back_button_interceptor))

You can probably implement this by adding code to the native app (intercept the event before the flutter framework, then pass the event to the app using [platform channel](https://flutter.dev/docs/development/platform-integration/platform-channels)), or by patching flutter itself. Unfortunately these are not in my skill range.

I'll file an issue about this to the flutter repo.

A possible workaround for now is to close the popup at the same time when the keyboard closes, so both the popup and keyboard closes when the user presses the back button. Would you like me to implement that?

**Comment by Bubu** [comment]
> A possible workaround for now is to close the popup at the same time when the keyboard closes, so both the popup and keyboard closes when the user presses the back button. Would you like me to implement that?

That *does* sounds like a good compromise until flutter makes way for a better solution.

>  Would you like me to implement that?

Uhm, it sure would be nice to have that, but please don't feel obligated to do anything for some random person opening an issue in your github repo :upside_down_face:.

**Comment by PegasisForever** [comment]
I'm using [flutter_keyboard_visibility](https://pub.dev/packages/flutter_keyboard_visibility) to implement this, however this package doesn't work on the web, is that a big deal for you?

**Comment by Bubu** [comment]
Mobile web browsers aren't really in our scope, no. :)

**Comment by PegasisForever** [comment]
New version published as `2.0.5`.
